/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.xh123.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
    private final TextPlayer player1;
    private final TextPlayer player2;

    /**
     * Constructs the object of App type.
     * 
     * @param width       is the width of the Board
     * @param height      is the height of the Board
     * @param inputSource is where to read input String.
     * @param out         is where to print Board's text view.
     */
    public App(int width, int height, Reader inputSource, PrintStream out) {
        Board<Character> b1 = new BattleShipBoard<Character>(width, height);
        Board<Character> b2 = new BattleShipBoard<Character>(width, height);
        BufferedReader input = new BufferedReader(new InputStreamReader(System.in));
        V1ShipFactory factory = new V1ShipFactory();
        this.player1 = new TextPlayer("A", b1, input, System.out, factory);
        this.player2 = new TextPlayer("B", b2, input, System.out, factory);
    }

    /**
     * This makes the program read input String from inputSource, create a new ship
     * and try to add it into the Board, then print the current view of the Board.
     * 
     * @throws IOException If We Have Io Errors When Reading Or Printing.
     */
    public void doPlacementPhase() throws IOException {
        player1.doPlacementPhase();
        player2.doPlacementPhase();
    }

    /**
     * The entry point of the entire program.
     * 
     * @throws IOException If We Have Io Errors When Reading Or Printing.
     */
    public static void main(String[] args) throws IOException {
        App app = new App(10, 20, new InputStreamReader(System.in), System.out);
        app.doPlacementPhase();
    }
}
