/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.xh123.battleship;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintStream;
import java.io.Reader;

public class App {
    private final Board<Character> theBoard;
    private final BoardTextView view;
    private final BufferedReader inputReader;
    private final PrintStream out;

    /**
     * Constructs the object of App type.
     * 
     * @param theBoard    is the specified text Board for our BattleShip Game.
     * @param inputSource is where to read input String.
     * @param out         is where to print Board's text view.
     */
    public App(Board<Character> theBoard, Reader inputSource, PrintStream out) {
        this.theBoard = theBoard;
        this.view = new BoardTextView(theBoard);
        this.inputReader = new BufferedReader(inputSource);
        this.out = out;
    }

    /**
     * This makes the program read input String from inputSource.
     * 
     * @param prompt is the message to prompt user input some String.
     * @return the Placement information.
     * @throws IOException if we have IO errors when reading or printing.
     */
    public Placement readPlacement(String prompt) throws IOException {
        out.println(prompt);
        String s = inputReader.readLine();
        return new Placement(s);
    }

    /**
     * This makes the program read input String from inputSource, create a new ship
     * and try to add it into the Board, then print the current view of the Board.
     * 
     * @throws IOException If We Have Io Errors When Reading Or Printing.
     */
    public void doOnePlacement() throws IOException {
        Placement p = readPlacement("Where would you like to put your ship?");
        BasicShip basic_ship = new BasicShip(p.getCoordinate());
        theBoard.tryAddShip(basic_ship);
        out.print(view.displayMyOwnBoard());
    }

    /**
     * The entry point of the entire program.
     * 
     * @throws IOException If We Have Io Errors When Reading Or Printing.
     */
    public static void main(String[] args) throws IOException {
        Board<Character> b = new BattleShipBoard<>(10, 20);
        App app = new App(b, new InputStreamReader(System.in), System.out);
        app.doOnePlacement();
    }
}
